version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - /mnt/datos-tfg/mysql:/var/lib/mysql

  fastify-server:
    build: ./server 
    container_name: fastify_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      DB_HOST: mariadb
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: mydatabase
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    depends_on:
      - mariadb

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_dashboard
    restart: always
    ports:
      - "3001:3000" # Mapeamos al 3001 porque el 3000 lo usa fastify  
    environment:
      - GF_SECURITY_ADMIN_USER=admin      # Usuario inicial
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Contrase√±a inicial
    volumes:
      - grafana_data:/var/lib/grafana     # Volumen para persistir dashboards y usuarios
    depends_on:
      - mariadb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_metrics
    restart: always
    ports:
      - "9090:9090"
    volumes:
      # Necesitas crear este archivo localmente primero (ver paso 2)
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    restart: always
    ports:
      - "9104:9104"
    volumes:
      - ./my.cnf:/etc/my.cnf
    command:
      - '--config.my-cnf=/etc/my.cnf'
    depends_on:
      - mariadb

# Definimos el volumen persistente para Grafana
volumes:
  grafana_data:
