global:
  scrape_interval: 15s

scrape_configs:
  # 1. Prometheus se vigila a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Fastify (Tu aplicación)
  - job_name: 'fastify-app'
    static_configs:
      # Usamos el nombre del servicio de docker y el puerto interno
      - targets: ['fastify-server:3000']
    # OJO: Prometheus buscará por defecto la ruta /metrics. 
    # Asegúrate de que tu Fastify expone métricas en esa URL.

  # 3. MariaDB (A través del Exporter)
  - job_name: 'mariadb'
    static_configs:
      # No apuntamos a la base de datos, sino al exporter (el traductor)
      - targets: ['mysqld-exporter:9104']